name: Feature Request
description: File a Feature Request
title: "[Feat request]: "
labels: ["enhancement"]
assignees:
  - imcelroy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest improvements!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: What is the feature?
      description: Please describe the new feature in as much detail as possible
      placeholder: Details here...
      value: "Details!"
    validations:
      required: true
